version: '3.8'

services:
  graphql-web-api:
    container_name: web-api
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env
      # Only will build development stage from our dockerfile
      target: development
    environment:
      DATABASE_URL: postgresql://postgres:superuser@postgres:5432/graphql-movies-db?schema=public
    volumes:
      - ./api:/app
#      - /app/node_modules
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: graphql-movies-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuser
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  docker-nest-postgres: